# Generated by Django 3.1.7 on 2022-03-23 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achuus', '0009_auto_20220321_2016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='achuu_Profile',
            new_name='AchuuProfile',
        ),
    ]
