# Generated by Django 3.1.7 on 2022-02-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220224_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Danger', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='blog.Ingredients'),
        ),
    ]
