# Generated by Django 3.1.7 on 2022-02-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220225_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
